export const Color = {
    color_bg: '#FFFFFF',
    color_black: '#000000',
    color_text_light: '#8D8D8D',
    color_text_header_inactive: '#1F1F1F',
    color_select: '#E0E0E0',
    color_social_media_circle: '#1B1B1B',
    color_footer_join_newsletter: '#131313',
    color_circle_big: '#1A1A1A',
    color_input_dark_background: '#1E1E1E',
    color_circle_fade: '#484848',
    color_input_dark_placeholder: '#616161',
    color_contact_us_title_subtitle: '#717171',
    color_input: '#848484',
    color_contact_us_content_contact_subtitle: '#C9C9C9',
    color_hover: '#FBFBFB',
}